### ISSUE TITLE
Concurrency/Batching API

### ISSUE THREAD

**Issue by klimesf** [klimesf/a4m36jee-project#14]

**Comment by ondrakrat** [comment]
"Zároveň je potřeba nahrávat seznam letů ve formátu CSV pomocí dávkových operací." - to udělám přes batching a budu to volat přes REST API, čímž pokrejeme požadavek "Aplikace bude volat alespoń jeden REST endpoint (JAX-RS)"

**Comment by klimesf** [comment]
Jakože interně ta aplikace bude volat svuj REST? Trochu krkolomný, ale co by člověk pro splnění požadavků neudělal :D
