### ISSUE TITLE
Předělat dokumentaci k REST, přidat authentication

### ISSUE THREAD

**Issue by klimesf** [klimesf/a4m36jee-project#29]

**Comment by ondrakrat** [comment]
@klimesf Je tam autorizace na práva, ale je to ve web.xml, přes ty anotace mi to z nějakýho důvodu nefungovalo. Jdu teď kouknout na batching, pak to zkusím ještě předělat, protože se mi to takhle nelíbí :)

**Comment by klimesf** [comment]
@ondrakrat To jo, ale předpokládám že když posíláš požadavek na REST kterej je zabezpečenej, tak musíš poslat něco jako `-H 'Authorization: Basic abcd123'`, ne? :)

**Comment by ondrakrat** [comment]
zkoušel jsem to curlem s --user username:password, což nefungovalo.

**Comment by klimesf** [comment]
Ajaj, a jak se tam teď dostanem? :D

**Comment by ondrakrat** [comment]
No, ty posty jsem nevymyslel. Co bych měl posílat v tom auth headeru? Když jsem poslal JSESSION_ID, tak mi to taky hodí login

**Comment by klimesf** [comment]
Ještě mě napadá `http://username:password@localhost:8080/airlines/rest/abc`

**Comment by klimesf** [comment]
V headeru se dělá [base64encode](https://www.base64encode.org) "username:password", takže pro `admin:admin` by to bylo `-H 'Authorization: Basic YWRtaW46YWRtaW4='`

**Comment by ondrakrat** [comment]
Hm, všechno vrací to samý...vyřešíme později? :)

**Comment by klimesf** [comment]
Ok

**Comment by ondrakrat** [comment]
authentication and authorization finished
